# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Michał Buczek
tagline:          'iOS/Swift freelancer'
description:      'iOS/Swift developer and Football Freestyler. Living in Poland. This site is my porfolio and technical blog(soon)'
url:              http://michalbuczek.com
baseurl:          /

author:
  name:           'Michał Buczek'
  url:            https://github.com/iccub

paginate:         5

# Custom vars
version:          2.1.0

github:           
  repo:           https://github.com/iccub
